### ISSUE TITLE
”removing-all“issues

### ISSUE THREAD

**Issue by Highrii** [TiaTheFairy/TiaGrindstoneEnhanced#1]
hi请问你是国人吗？很好的插件，但是还是有很多问题。
1 在removing-all中，我不知道count-all价格是怎样计算的；
2 removing-all的%price%占位符也有显示问题，在砂轮的图标上总是多显示一个%；
3 removing-all设置为none后，GUI右上角在打开时仍然有一个空槽，这很不美观
所以我认为可以在config中加一个removing-all的开关选项，然后希望可以添加playerpoints支持，感谢

Hi, may I ask if you are Chinese? It's a great plugin, but there are still many issues.
1 In removing-all, I don't know how the count-all price is calculated.
2 The %price% placeholder in removing-all also has a display issue, where an extra % is always shown on the grindstone icon.
3 When removing-all is set to none, there is still an empty slot in the upper right corner of the GUI when it opens, which is not aesthetically pleasing.
So I think it would be good to add an option to enable/disable removing-all in the config, and I hope you can add support for PlayerPoints.
Thank you!

**Comment by Tia-Nina** [comment]
removing-all的count-all模式将会根据removing-single中设置的per-level价格计算每个附魔的移除费用并相加，然后用removing-all的type作为费用类型。

针对占位符解析和新增removing-all开关的问题，我会尽快处理并在下个版本中添加修复。

关于PlayerPoints，我会考虑在后续版本中添加支持，感谢支持。

**Comment by Tia-Nina** [comment]
Now support PlayerPoints. Download latest in SpigotMC
